### ISSUE TITLE
toJavaScript() throws "Cannot read property 'text' of undefined" error with typescript@2.1.5

### ISSUE THREAD

**Issue by NewGyu** [teppeis/typescript-simple#68]
## phenomenon

```
$ $(npm bin)/mocha
TypeError: Cannot read property 'text' of undefined
    at TypeScriptSimple.toJavaScript (/home/newgyu/Desktop/kms-vault/node_modules/typescript-simple/index.js:190:28)
    at TypeScriptSimple.compile (/home/newgyu/Desktop/kms-vault/node_modules/typescript-simple/index.js:70:25)
    at Object.loadTypeScript (/home/newgyu/Desktop/kms-vault/node_modules/espower-typescript/index.js:19:22)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at /home/newgyu/Desktop/kms-vault/node_modules/mocha/lib/mocha.js:222:27
    at Array.forEach (native)
    at Mocha.loadFiles (/home/newgyu/Desktop/kms-vault/node_modules/mocha/lib/mocha.js:219:14)
    at Mocha.run (/home/newgyu/Desktop/kms-vault/node_modules/mocha/lib/mocha.js:487:10)
    at Object.<anonymous> (/home/newgyu/Desktop/kms-vault/node_modules/mocha/bin/_mocha:459:18)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:509:3

```

### directories

```
.
├── dist
├── node_modules
├── package.json
├── src
├── test
│   ├── index.test.ts
│   └── mocha.opts
└── tsconfig.json
```

after tsc compile

```
./dist
├── src
└── test
    └── index.test.js
```

### tsconfig.json
```
{
  "compileOnSave": true,
  "compilerOptions": {
    "outDir": "./dist",
    "target": "es5",
    "module": "commonjs",
    "moduleResolution": "Node",
    "lib": [
      "es2015",
      "es2015.promise",
      "es2015.generator"
    ],
    "types": [
      "node"
    ],
    "allowJs": true,
    "noImplicitAny": true,
    "strictNullChecks": true
  },
  "include": [
    "./src/**/*",
    "./test/**/*"
  ]
}
```

### mocha.opts

```
--compilers ts:espower-typescript/guess test/**/*.ts
--recursive
```

## I guessed ...

https://github.com/teppeis/typescript-simple/blob/75d7cf0413a3f7ee2aa77a38c50e5d011cae5ae5/index.ts#L169
```
            let output = service.getEmitOutput(fileName);
```

https://github.com/teppeis/typescript-simple/blob/75d7cf0413a3f7ee2aa77a38c50e5d011cae5ae5/index.ts#L184-L191
```
            let outputFileName: string;
            if (this.options.jsx === ts.JsxEmit.Preserve) {
                outputFileName = path.join(outDir, fileNameWithoutRoot.replace(/\.tsx$/, '.jsx'));
            } else {
                outputFileName = path.join(outDir, fileNameWithoutRoot.replace(/\.tsx?$/, '.js'));
            }
            // for Windows #37
            outputFileName = this.normalizeSlashes(outputFileName);
```

|var   |value                  |
|:------|:---------------|
|output.name|`/home/newgyu/Desktop/kms-vault/dist/index.test.js`|
|outputFileName|`/home/newgyu/Desktop/kms-vault/dist/test/index.test.js`|

I think `output.name` must be `/home/newgyu/Desktop/kms-vault/dist/test/index.test.js` , because test-source path is `./test/index.test.ts` and transpiled file is put `./dist/test/index.test.js`.

Is this a problem of Typescript ? Or is this related to typescript-simple ?

**Comment by NewGyu** [comment]
I am using the following versions.
```
typescript@2.1.5
power-assert@1.4.2
espower-typescript@7.0.0
typescript-simple@7.0.2
mocha@3.2.0
```

**Comment by izumin5210** [comment]
I could also reproduce the same error on the following repository:

https://github.com/izumin5210-sandbox/typescript-and-power-assert-sample/blob/535de1b57972dde34531570bbd66e2b5219601bc/test/sample-spec.ts

| var | value |
| --- | --- |
| fileName | `test/sample-spec.ts` |
| output | `{ outputFiles: [], emitSkipped: true }` |
| outDir | (empty string) |
| outputFileName | `test/sample-spec.ts` |

**Comment by NewGyu** [comment]
I tried again today. Then... I could not reproduce the error that I reported.
But, I don't understand why I could not reproduce.

For reference, this is the source code that is no longer reproduced.
https://github.com/NewGyu/typescript-mocha-power-assert

But, the error is reproduced on @izumin5210 's source code.

**Comment by ddgenome** [comment]
I am seeing this error as well. To recreate:

Clone https://github.com/ddgenome/ts-undefined

```
$ git clone https://github.com/ddgenome/ts-undefined.git
$ cd ts-undefined 
```

If you do not have yarn installed

```
$ npm install -g yarn@0.23.4
```

Install dependencies

```
$ yarn
```

Try to run tests

```
$ yarn mocha
yarn mocha v0.23.4
$ mocha --compilers ts:espower-typescript/guess 'mocha/**/*.ts'
.../node_modules/typescript-simple/index.js:182
            var text = file.text;
                           ^

TypeError: Cannot read property 'text' of undefined
    at TypeScriptSimple.toJavaScript (.../node_modules/typescript-simple/index.js:182:28)
    at TypeScriptSimple.compile (.../node_modules/typescript-simple/index.js:69:25)
    at Object.loadTypeScript (.../node_modules/espower-typescript/index.js:19:22)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at .../node_modules/mocha/lib/mocha.js:230:27
    at Array.forEach (native)
    at Mocha.loadFiles (.../node_modules/mocha/lib/mocha.js:227:14)
    at Mocha.run (.../node_modules/mocha/lib/mocha.js:495:10)
    at Object.<anonymous> (.../node_modules/mocha/bin/_mocha:460:18)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.runMain (module.js:605:10)
    at run (bootstrap_node.js:423:7)
    at startup (bootstrap_node.js:147:9)
    at bootstrap_node.js:538:3
error Command failed with exit code 1.
```

Make sure everything is actually OK with the code in the repo

```
$ $(yarn bin)/mocha 'target/ts-built/mocha/**/*.js'


  success
    ✓ should be true


  1 passing (6ms)

```

**Comment by ddgenome** [comment]
It seems the issue is with the TypeScript compiler.

I was able to get things working by adding `"rootDir": "."` to the tsconfig.json "compilerOptions".

This gave me a hint: https://github.com/Microsoft/TypeScript/issues/5134
