### ISSUE TITLE
Import statement fails to be compiled

### ISSUE THREAD

**Issue by nearbydelta** [teppeis/typescript-simple#87]
The following code is not working properly:
```javascript
var TypeScriptSimple = require('typescript-simple').TypeScriptSimple;
var tss = new TypeScriptSimple({module:'commonjs'});
tss.compile('import * as fs from "fs"');
```

The third line reports following error:
```
Error: L0: Cannot find module 'fs'.
    at TypeScriptSimple.toJavaScript (/.../node_modules/typescript-simple/index.js:162:23)
    at TypeScriptSimple.compile (/.../node_modules/typescript-simple/index.js:73:25)
    at repl:1:5
    at sigintHandlersWrap (vm.js:22:35)
    at sigintHandlersWrap (vm.js:73:12)
    at ContextifyScript.Script.runInThisContext (vm.js:21:12)
    at REPLServer.defaultEval (repl.js:340:29)
    at bound (domain.js:280:14)
    at REPLServer.runBound [as eval] (domain.js:293:12)
    at REPLServer.<anonymous> (repl.js:538:10)
```

I know that I can turn off this error by passing second argument `false` to constructor of TSS, but I have to make a type checker with semantic checking. Am I using TSS in the right way?

**Comment by teppeis** [comment]
@nearbydelta yes, it's a limitation of typescript-simple.

> Limitations
> typescript-simple cannot compile multiple source files.
> https://github.com/teppeis/typescript-simple#limitations

You can ignore all semantic errors by 2nd argument or remove dependencies on external resources.
It's by design.
Using external module (which module? how typing?) needs too complicated work around.
If you need, use TypeScript native APIs directly.
Thanks!
